### ISSUE TITLE
Remove fluent asserts from raylib

### ISSUE THREAD

**Issue by crazymonkyyy** [schveiguy/raylib-d#12]
```d
version (unittest)
{
    import fluent.asserts;
}
```
pls delete this dead dependency from raymathext.d

**Comment by schveiguy** [comment]
This is not a dead dependency, the unittests use fluent asserts. Though I'm not sure we need it, I'm willing to accept a PR that switches to regular asserts.

**Comment by schveiguy** [comment]
Done in 4.2.0
