### ISSUE TITLE
raylibVersion symbol not included in MSVC DLL for raylib 4.2.0

### ISSUE THREAD

**Issue by schveiguy** [schveiguy/raylib-d#21]
In https://github.com/raysan5/raylib/issues/2671 it was noted that the MSVC dll for raylib 4.2.0 doesn't properly export the raylibVersion symbol.

The fix is simple. But there will not be a new binary built! So we can include the DLL directly on our repository. However, if we start going that route, we may as well just include them all. Or at least set up a way to download them all.

My first inclination is to include all the pre-packaged binaries on the repository, and then provide a sub-project to install it to the right place -- either your project directory (Windows) or /usr/local/lib (Posix). Then building can be done without having to properly install the lib files.

**Comment by EugZol** [comment]
Would be helpful if this was solved and binding actually worked :)

**Comment by schveiguy** [comment]
Sorry. I fear there is zero chance that Ray will fix the official build. The only thing I can do is either a) disable the function in windows, or b) provide my own corrected build.

I will see if I can in the next week make a build on Windows. I don't have a Windows system that I use regularly, so it's a process...

**Comment by EugZol** [comment]
No worries, thanks for your work! I don't know much about C or D ecosystems and how things work traditionally but including bundling dll in the bindings seems like a good idea to me.

**Comment by schveiguy** [comment]
Please try out the new raylib-d install script in 4.2.1 and see if it fixes your issue.

**Comment by schveiguy** [comment]
I'm satisfied this is fixed.
