### ISSUE TITLE
Using arrays in vectors

### ISSUE THREAD

**Issue by al1-ce** [schveiguy/raylib-d#36]
Have vectors in this format:
```d
struct Vector2 {
    float data[2] = [0.0f, 0.0f];
    alias data this;
    void x(float _x) { x = _x;} 
    float x() { return x;} 
    // same for y
    mixin Linear;
}
```
To allow usage of other libraries/custom vector implementations

**Comment by al1-ce** [comment]
I assume aliases would do something similar then
Well, making my own wrapper anyway

Still, toArray and fromArray would be appreciated if not a burden to do

**Comment by schveiguy** [comment]
Such an implementation is trivial, if you want to include it for your external projects.

```d
ref float[2] toArray(ref Vector2 v)
{
   return *cast(float[2]*)&v;
}

v.toArray[0] = 5;
assert(v.x == 5);
```
