### ISSUE TITLE
Raylib-D does not work with the 32-bit version of raylib

### ISSUE THREAD

**Issue by ninjaraven** [schveiguy/raylib-d#37]
Raylib's 32-bit version is not included in the install script, and everything I've tried so far doesn't help it.

(was told to put this issue here by the maintainer)

**Comment by schveiguy** [comment]
I have updated the install script and the library tarball.

Can you update your dependency to 4.5.2 and see if it works? I just put the win32 libs in there, I didn't test on a win32 installation.

**Comment by schveiguy** [comment]
Also, apologies for the long time coming. This has been a crazy year for me!

**Comment by schveiguy** [comment]
Closing this as fixed. Please let me know if it doesn't work for you.
