### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by SpiceyWolf** [schveiguy/raylib-d#4]
Just wondering cause its been a hot minute and I seen on the pull request for 3.7 update a response was made that this is (assumed) to operate on 3.0 still...

If its pretty much floating on user submissions Ill happily update everything to the latest in the next couple weeks and submit a pull request (as long as itll go somewhere). If a submission would be accepted I'd include some pre-compiled binaries so its a little more........ accessible >_>

**Comment by schveiguy** [comment]
Not dead! The history is -- onroundit deleted his github account. I was teaching a class that used raylib-d, so I resurrected it, and now I maintain the dub dependency. Though I barely have ever used raylib, I will make sure it doesn't go away again.

But the result is that this code base is not well maintained (lots of broken links ATM, and the wiki has been lost), I'm not very well-versed in raylib or graphics programming, I'm just someone trying to teach some code, and tinker, though I have really good expertise in D. But I surely don't have experience with most of raylib, nor rely on it for a real project.

Please coordinate with @Soaku as he has done some preliminary work (in the PR you mentioned) to update to the latest version. I'd prefer a solution that doesn't involve hand-translation, but I think that is the stage we are currently at. More ideas welcome, and certainly contributions welcome! I would just hate to have folks do repeat efforts.

**Comment by SpiceyWolf** [comment]
In complete fairness, I don't see a super convenient way to automate the binding, mostly because raylib isn't structured as cleanly as most sources. Its stuff is a little scattered, their documentation on building only seems to care about a unix environment (making it a pain for new users who just wanna pull and be ready to use, at least on windows) and afaik the bindings made with D usually still require some manual work every time anyway after it's done.

I don't mind being a common contributor to keep it up to date though, I got lots of exp making bindings and used to maintain some for sfml until I moved to D exclusively c:

**Comment by Soaku** [comment]
Probably we should use a binding generator and manually edit it to add old functionality, since raylib-d *clearly* was made with a generator first. But this topic should be continued in #3.

I use Raylib as a primary part of my major project, so I'm willing to maintain/help maintain raylib-d.

> Its stuff is a little scattered, their documentation on building only seems to care about a unix environment

Raylib wiki (https://github.com/raysan5/raylib/wiki/) has resources on Windows too, and most people using Raylib seem to be Windows users since it's meant to be beginner-friendly. 

In case of Raylib-d, just get the raylib libraries and add `"libs": ["raylib"]` to dub. With Windows you'll need to make sure you place Raylib in your library search directories… and I'm afraid I can't help with that one.

**Comment by Hezkore** [comment]
Any news on progress?
I've recently started using D, and I've used Raylib in the past, so an updated Raylib version would be great.

**Comment by Soaku** [comment]
@Hezkore I haven't done much except for the single commit in #3 which I'll probably rollback anyway. I should definitely get into this once I'm done with the current goal in my own project.

The current bindings work pretty well and work with the newer versions as well, but you might find some missing symbols. Most of the time it should be enough to just define your own module that would add them.

**Comment by Hezkore** [comment]
I haven't been able to link against the static library on any platform so far.
Admittedly I don't know exactly what I'm doing... but I figured the reason was because the module hasn't been updated to the newer Raylib versions.

**Comment by Soaku** [comment]
I don't think that would be the reason. I've been able to link 3.5.0 and 3.7.0 successfully without issues — statically on Linux and dynamically on Windows.

`"libs": ["raylib"]` in `dub.json` is enough if you have Raylib correctly installed in the system, at least on Linux, I know it's probably a bit more complex on Windows.

**Comment by schveiguy** [comment]
> I haven't been able to link against the static library on any platform so far.

If you could open a separate issue with the exact details, we may be able to help. I have had no problem linking against the binary distributions of raylib from 3.0.0 on both Mac and Windows, I haven't tried anything later, but it's possible there's an issue somewhere.

**Comment by schveiguy** [comment]
I've merged the updates (so far), will have a release soon to publish. I'm going to close this, as the issue in the title has been answered. Feel free to open more issues if you still have problems.
