### ISSUE TITLE
Microscopic issue in a comment causes tons of warnings when using document builder

### ISSUE THREAD

**Issue by cdcrchrisparker** [schveiguy/raylib-d#47]
This is in the comments only, hence does not affect code at all.  There is a missing right paren in the comments for source/raylib/rlgl.d - this missing paren causes dozens of warnings whenever one uses the document generator.  E.g. 

dub build --build=docs

The solution?  Line 78 of source/raylib/rlgl.d needs a trailing closing paren.

#define RL_DEFAULT_SHADER_UNIFORM_NAME_NORMAL      "matNormal"         // normal matrix (transpose(inverse(matModelView))**)**

**Comment by schveiguy** [comment]
Please file in raylib upstream as well (if not already fixed) -- rlgl is mechanically translated using dstep.

**Comment by cdcrchrisparker** [comment]
Oh - okay.  Didn't know that, I'll do so now.  :)

**Comment by schveiguy** [comment]
Also, the doc builder is going to suck -- none of the docs will be used since they are only double-slash. I need to do some kind of mechanical translation of the raylib comments to ddoc comments.

See also #13

**Comment by schveiguy** [comment]
Please let me know if that works -- https://github.com/schveiguy/raylib-d/commit/9906279494f1f83b2c4c9550779d46962af7c342

I may not do a release unless you really need it, as this affects nothing normally used.

**Comment by cdcrchrisparker** [comment]
I'm actually only interested in my own documentation, and was mildly surprised that the doc builder builds library stuff as well.

Having said that, I _might_ some spare cycles helping out with DDOC at some point in the near future.

**Comment by schveiguy** [comment]
OK, I'll do a release so it doesn't affect your project, sorry.

**Comment by cdcrchrisparker** [comment]
I edited my own version by hand.  Not to worry about the release, it's not an issue at all.  I just thought you'd like to know since it **looks** horrible when generating docs, and has such a simple resolution.

**Comment by schveiguy** [comment]
Well, I already did it ;) Not a huge deal.

**Comment by schveiguy** [comment]
> Having said that, I _might_ some spare cycles helping out with DDOC at some point in the near future.

That would be really great!
