### ISSUE TITLE
cheatsheet - 404

### ISSUE THREAD

**Issue by vitalfadeev** [schveiguy/raylib-d#5]
https://github.com/onroundit/raylib-d/wiki/Docs-(cheatsheet)
404

![Screenshot from 2021-08-21 09-56-37](https://user-images.githubusercontent.com/24979554/130308387-84c54590-a72e-428b-a98f-d0a67bbae3fa.png)

**Comment by schveiguy** [comment]
Yep, I know. That's why there's the note saying its missing. All the Wiki stuff was destroyed when onroundit deleted his github account.

**Comment by schveiguy** [comment]
FYI: #6
