### ISSUE TITLE
Remove linear mixin

### ISSUE THREAD

**Issue by schveiguy** [schveiguy/raylib-d#54]
The mixin just obscures what members are on the type, including operator overloads. The mixin also has weird static ifs to prevent overloads on things that it doesn't support, which is exactly backwards.

I'd rather just repeat the correct overloads for each type in the type, not as a template. This also will help IDEs.

Also, `zero` and `one` should be enums.

**Comment by Kapendev** [comment]
Can you explain more how a better solution would look like? Something like this?
```d
struct Vector2 {
    inout T opUnary(string op)() if (op == "+" || op == "-") {
        // ...
    }
    // ...
}
struct Vector3 {
    inout T opUnary(string op)() if (op == "+" || op == "-") {
        // ...
    }
    // ...
}
```

**Comment by schveiguy** [comment]
Yes, I want to just replace the mixin with the equivalent code from the operators.
