### ISSUE TITLE
Try to resurrect some of the wiki

### ISSUE THREAD

**Issue by schveiguy** [schveiguy/raylib-d#6]
There are some wiki pages available on the wayback machine from onroundit's account. we should try to resurrect some of those if possible.

For reference, here is one snapshot: https://web.archive.org/web/20201210034335/https://github.com/onroundit/raylib-d

It doesn't contain all the wiki pages though, maybe other snapshots will.

**Comment by SpiceyWolf** [comment]
For the docs/cheatsheet, shouldnt it just link to the official one from raylib website? In practice it should be verbatum the same usage in D... and always up to date since they are kinda maintaining the thing for their own library lol

Outside the 'how to get this binder working with D' which is already in the readme, I dont see anything further being relevant :P

**Comment by SpiceyWolf** [comment]
Here:
https://www.raylib.com/cheatsheet/cheatsheet.html

**Comment by schveiguy** [comment]
There was a D-specific cheatsheet in the wiki in onroundit's account (hence the link). I didn't use it, so I don't know what was different about it. It would be nice to have some documentation on using the improved API that we have here (e.g. the operator overloads).

I probably could update the URL to just point at raylib's cheatsheet. But I didn't want to do that yet when there's a chance we can resurrect the old one (not sure if there are any other wayback snapshots that have it in there).

**Comment by SpiceyWolf** [comment]
I already checked a few archive sites and couldnt find anything linking into files on that repository :/

**Comment by schveiguy** [comment]
ugh, I checked wayback, that's the only snapshot. So we are probably out of luck. I'll ask webfreak if he saved the wiki repo (he had a copy of the git repo, which is how I resurrected it).

**Comment by schveiguy** [comment]
Some more info: if the snapshot is to be believed, the wiki only has 3 pages, the home page, the "Installation" page, and the cheatsheet. Only the cheatsheet is missing.

This should be pretty easy to recover, and we can probably just point at the official cheatsheet.

**Comment by schveiguy** [comment]
I'm giving up on this. Wiki isn't a great place to put this anyway.
